{% set name = "ngmix-split" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/ngmix/archive/v{{ version }}.tar.gz
  sha256: 0e1cb66643ef8a75a5b993b257d58c90fb30e1ba5b34e2cb5345d674f616d82c

build:
  number: 1
  skip: true  # [win]

outputs:
  - name: ngmix-core
    script: build_core.sh
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
      run:
        - python
        - numpy
        - numba <0.41.0a|>=0.43.0,!=0.54.0  # bug in these numbas
        - scipy
        - galsim

    test:
      imports:
        - ngmix

  - name: ngmix
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("ngmix-core", exact=True) }}
        - meds
    test:
      imports:
        - ngmix
        - ngmix.medsreaders

about:
  home: https://github.com/esheldon/ngmix
  license: GPL-2.0-only
  license_family: GPL
  license_file: gpl.txt
  summary: Gaussian mixtures and image processing implemented in python and numba

extra:
  recipe-maintainers:
    - beckermr
